### ISSUE TITLE
Sliders exercise component (Participant POV)

### ISSUE THREAD

**Issue by asyarb** [WalltoWall/workshop-v2#1]
Feel free to drop in any long-form questions and/or discussions in here and tag me! Sometimes discussing code may be easier in Github.

**Comment by davidjcreative** [comment]
- [x] Mark up
- [x] Sanity Content Integration 
- [x] Item images
- [x] Item title
- [x] Range Slider
- [ ] Image switch
- [ ] Submit answer Data
